stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - ./deploy.sh  # You may replace this with your deployment script
  only:
    - main  # Deploy only when changes are pushed to the master branch
